kind: pipeline
type: docker
name: node16

platform:
  os: linux
services:
  - name: Clickhouse-20.3
    image: yandex/clickhouse-server:20.3
steps:
  - name: install
    image: node:latest
    environment:
      PORT: "8080"
      BUILD_VERSION: "1.0.1"
      NODE_ENV: "test"
      SERVICE_NAME: "quota"
      CLICKHOUSE_HOST: "0.0.0.0"
      CLICKHOUSE_PORT: "8123"
      CLICKHOUSE_DB: "default"
      CLICKHOUSE_FORMAT: "tsv"
      AWS_REGION: "us-east-1"
      LOG_LEVEL: "debug"
      RUN_LOCAL: "true"
    commands:
      - pwd -P; ls -1 -A
      - npm i -g npm
      - echo  '@rapidapi:registry=https://npm.pkg.github.com' >>.npmrc
      - echo '//npm.pkg.github.com/:_authToken=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' >> .npmrc
      - cat .npmrc > ~/.npmrc
      - npm install @rapidapi/rapid-logger
      - npm install @rapidapi/rapid-metrics
      - npm install 
      - echo 'PORT = 8080' >> ./config/.test.env
      - echo 'BUILD_VERSION = 1.0.1' >> ./config/.test.env
      - echo 'NODE_ENV = test' >> ./config/.test.env
      - echo 'SERVICE_NAME = quota' >> ./config/.test.env
      - echo 'CLICKHOUSE_HOST = 0.0.0.0' >> ./config/.test.env
      - echo 'CLICKHOUSE_PORT = 8123' >> ./config/.test.env
      - echo 'CLICKHOUSE_DB = default' >> ./config/.test.env
      - echo 'CLICKHOUSE_FORMAT = "tsv"' >> ./config/.test.env
      - echo 'AWS_REGION = us-east-1' >> ./config/.test.env
      - echo 'LOG_LEVEL = debug' >> ./config/.test.env
      - echo 'RUN_LOCAL=true' >> ./config/.test.env
      - ls -lAtr
      - sleep 30
      - ./tableCreate.sh
      - npm test ./test
