name: On release - deploy to staging

on: 
  release:
    types: [created]

jobs:
  deployReleaseToStaging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get tag name
      id: get_tag
      run: |
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: call Jenkins
      run: |
        curl --request POST \
        --url '${{ secrets.TRIGGER_JENKINS_URL }}' \
        --header 'Content-Type: application/json' \
        --data '{
                  "PARAMETERS": {
                    "SERVICE": "quota",
                    "GIT_SERVICE_NAME": "RapidAPI/quota-service",
                    "DEVOPS_GIT_BRANCH": "master",
                    "TAG_VERSION": "${{ steps.get_tag.outputs.SOURCE_TAG }}"
                  },
                  "TYPE": "backend",
                  "TOKEN": "${{ secrets.TRIGGER_JENKINS_TOKEN }}"
                }'